### ISSUE TITLE
Deletion of users

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#209]
Reason:
Currently, user accounts cannot be deleted because they are associated with subscriptions. Subscriptions, on the other hand, cannot be deleted because they are used to generate the statistics of the past years.
What should be done?

**Comment by TobiMarg** [comment]
Instead of deleting old courses I would prefer something like creating a placeholder user which takes over all subscriptions from all deleted users.

In general, it may be useful to think about how long we need which information and if and when we can (or should) delete what. Then we could automatically clean up old and unnecessary stuff, while being sure that nothing important gets deleted.
