### ISSUE TITLE
Voucher Download Joint PDF

### ISSUE THREAD

**Issue by renatobellotti** [tanzquotient/tq_website#70]
Doesn't work (error message).

**Comment by gitsimon** [comment]
Yes I broke this with knowing it. The chain of problems was:

1. alpine Linux versions as basis for docker docker containers was required to make image size smaller on server since space kind of limited

2. the django plugin (cairo) that we used to generate and join PDFs required some stuff to be installed on machine, which failed on Alpine Linux (see [commit](https://github.com/gitsimon/tq_website/commit/ac6df31bb05438c086764e087e0b262b95f70dfc))

3. Therefore, at the moment only SVG generation works, this has to be converted/joined on some other machine.

**Comment by martinzellner** [comment]
I think it should be generally possible to run cairo on alpine linux but it might require some troubleshooting.

**Comment by renatobellotti** [comment]
Another possibility is to use a python only solution: https://docs.djangoproject.com/en/2.0/howto/outputting-pdf/
